### ISSUE TITLE
Exception: Error: 503 Service Unavailable while searching authors

### ISSUE THREAD

**Issue by aritzzz** [OrganicIrradiation/scholarly#10]
This strange kind of problem is happening while I am searching for authors.
I am using 
`search = next(scholarly.search_author())` 
to get author's info.? But for some authors, it is returning search but for others this 
`Traceback (most recent call last):
  File "/home/rajeev/Desktop/work/Desktop/Rajeev/codestogeneratefeatures/write_auth_affl_file.py", line 42, in <module>
    print hindex('Zbigniew S Szewczak')
  File "/home/rajeev/Desktop/work/Desktop/Rajeev/codestogeneratefeatures/affl.py", line 29, in hindex
    search = next(scholarly.search_author(nameaffiliation))
  File "/home/rajeev/.local/lib/python2.7/site-packages/scholarly.py", line 296, in search_author
    soup = _get_soup(_HOST+url)
  File "/home/rajeev/.local/lib/python2.7/site-packages/scholarly.py", line 92, in _get_soup
    html = _get_page(pagerequest)
  File "/home/rajeev/.local/lib/python2.7/site-packages/scholarly.py", line 79, in _get_page
    raise Exception('Error: {0} {1}'.format(resp.status_code, resp.reason))
Exception: Error: 503 Service Unavailable` 
error is coming.

**Comment by OrganicIrradiation** [comment]
Are you still experiencing this issue?

**Comment by Tweedletween** [comment]
I am experiencing this issue, too.

**Comment by OrganicIrradiation** [comment]
It is most likely due to Google sending a CAPTCHA request, which is not currently handled.
