### ISSUE TITLE
Simple example usage fails on fresh install of Python 3.7.2 (AttributeError: 'NoneType' object has no attribute 'text')

### ISSUE THREAD

**Issue by hack-r** [OrganicIrradiation/scholarly#38]
This is running on Windows with Python 3 and a fresh install of `scholarly` from GitHub.

```
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import scholarly
>>> print(next(scholarly.search_author('Steven A. Cholewiak')))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\hackr\Python64\Python372\lib\site-packages\scholarly\scholarly.py", line 110, in _search_citation_soup
    yield Author(row)
  File "C:\Users\hackr\Python64\Python372\lib\site-packages\scholarly\scholarly.py", line 226, in __init__
    self.name = __data.find('h3', class_='gsc_oai_name').text
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by hack-r** [comment]
I am closing this because I found the same problem in another open Issue:

https://github.com/OrganicIrradiation/scholarly/issues/37
